{% set version = "2.9.1" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 2d6474576c08ee21d7f4f3a10fd1a47234fd9fd638efc8a2e0e64bb367f09bc1

build:
  number: 0
  skip: true  # [not linux]
  skip: true  # [cuda_compiler_version in ("None", "10.2")]
  run_exports:
    - {{ pin_subpackage('cutlass', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - make
  host:
    - cudnn
  run:
    - cudnn
test:
  commands:
    # shared:
    - test -f $PREFIX/lib/libcutlass.so               # [linux]
    - if not exist %LIBRARY_BIN%\cutlass.dll exit 1   # [win]

    # absence of static libraries (windows uses same extension for
    # static libs and the "import library" needed to load a DLL):
    - test ! -f $PREFIX/lib/libcutlass.a              # [not win]

    # headers:
    # This list should be substantially longer, but upstream just globs
    # all *.h files. These are the headers required for triton, but
    # relevant headers can be added as needed/desired.
    {% for each_header in ["library/handle.h", "library/library.h",
                           "library/operation_table.h", "library/singleton.h"] %}
    - test -f $PREFIX/include/cutlass/{{ each_header }} || (echo "{{ each_header }} not found" && exit 1)  # [unix]
    - if not exist %LIBRARY_INC%\cutlass\{{ "\\".join(each_header.split("/")) }} exit 1                    # [win]
    {% endfor %}

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - h-vetinari
