{% set version = "3.8.0" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 14a5e6314f23e41295d8377b6fa6028b35392757a0ee4538a4eacaaa5d7eee37

build:
  number: 0
  skip: true  # [osx or cuda_compiler_version not in ("12.6",)]
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja
  run_constrained:
    - cuda-version >=11.0.*,<13.a0

test:
  requires:
    - tree  # [linux]
  commands:
    # headers:
    - tree $CONDA_PREFIX/include/cutlass  # [linux]
    - tree $CONDA_PREFIX/include/cute  # [linux]
    - tree %CONDA_PREFIX%\Library\include\cutlass  # [win]
    - tree %CONDA_PREFIX%\Library\include\cute  # [win]

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - h-vetinari
    - RaulPPelaez
    - leofang
