{% set version = "4.2.0" %}

package:
  name: cutlass
  version: {{ version }}

source:
  url: https://github.com/NVIDIA/cutlass/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c9e965fdc8eddedb0fea0cf551ca6fd15dc7548d3cee6ce74e70cb393516ec15

build:
  number: 0
  skip: true  # [osx or cuda_compiler_version == "None"]
  ignore_run_exports_from:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}
    - cmake
    - ninja

test:
  requires:
    - tree  # [linux]
  commands:
    # headers:
    - tree $CONDA_PREFIX/include/cutlass  # [linux]
    - tree $CONDA_PREFIX/include/cute  # [linux]
    - tree %CONDA_PREFIX%\Library\include\cutlass  # [win]
    - tree %CONDA_PREFIX%\Library\include\cute  # [win]

about:
  home: https://github.com/NVIDIA/cutlass
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CUDA Templates for Linear Algebra Subroutines
  dev_url: https://github.com/NVIDIA/cutlass

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - h-vetinari
    - RaulPPelaez
    - leofang
